Repository eco-dessert-platform/dessert-front, pull requests merged in 2024-10, with the labels that each got.

#521 Fix : SEO > Dev 환경과 Main 환경 분리
  src/shared/utils/metadata.ts
  yarn.lock
Labels: bug

#529 ✨ Feat : robots 적용
  src/app/robots.ts
Labels: enhancement

#525 🐛 Fix : 찜 페이지 개선
  src/blocks/wish/(list)/products/WishFolderEditButtonSection.tsx
  src/domains/wish/components/WishFolder/index.tsx
  src/domains/wish/components/alert-box/DefaultFolderAlertPopup.tsx
  src/domains/wish/components/alert-box/DeleteWishFolderPopup.tsx
  src/domains/wish/components/alert-box/UpdateWishFolderModal.tsx
  src/domains/wish/constants/index.ts
Labels: bug, enhancement

#526 🐛 Fix : 찜 페이지 이미지에러 처리 및 디자인 수정
  public/assets/icons/bbangle-smile-small.svg
  src/domains/product/components/ProductCard/ProductImage/index.tsx
  src/domains/store/components/StoreCard.tsx
  src/domains/wish/components/common/FolderThumbnail.tsx
  src/domains/wish/queries/useDeleteWishProductMutation.ts
  src/shared/components/SadBbangleBox/index.tsx
  src/shared/components/icons/BbangleIcon.tsx
Labels: bug

#534 🐛 Fix : 찜 > API 성공 멘트 & 삭제 후 리스트 리패칭
  src/domains/wish/components/common/FolderThumbnail.tsx
  src/domains/wish/queries/useAddWishStoreMutation.ts
  src/domains/wish/queries/useDeleteWishProductMutation.ts
  src/domains/wish/queries/useDeleteWishStoreMutation.ts
Labels: bug

#536 🐛 Fix : 찜 > 동적 메세지 제공
  src/app/main/products/[productId]/info/_blocks/SimpleInfoWithStoreSection/DetailStoreInfo/index.tsx
  src/blocks/main/(detail)/products/[productId]/info/SimpleInfoWithStoreSection/DetailStoreInfo.tsx
  src/domains/store/components/StoreCard.tsx
  src/domains/wish/queries/useDeleteWishStoreMutation.ts
Labels: enhancement
